# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b61d1b60b4374a68082e5678c221d176d482db4d5a4fe34649e167a163186070b78ecbdf8262f95be5297e855a4b79f5ce5bc896d419957470f40edab1f3e15

test:
  secret_key_base: 9510166c53b5ef27ea67aaf80bbf4039c4f8a59082f268086ead90a00a36ea75d7ff2ee4054d67e24f8df35b2be02eff09e58af33bae26ac19602b10ec2a1eff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
